# Generated by Django 4.1.5 on 2023-01-31 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('body', models.TextField(blank=True, max_length=2000, null=True)),
                ('value', models.CharField(blank=True, choices=[('up', 'Up vote'), ('down', 'Down vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.tags'),
        ),
    ]
