# Generated by Django 4.1.5 on 2023-03-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('projects', '0002_projectsmodel_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
